version: "3.8"

services:
  brain:
    build:
      context: ../services/brain
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    restart: always

  nerves:
    build:
      context: ../services/nerves
      dockerfile: Dockerfile
    env_file:
      - ../.env
    depends_on:
      - brain
    restart: always

  face:
    build:
      context: ../services/face
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ../.env
    restart: always
